In [172]:
import pandas as pd 
import numpy as np
from sklearn.linear_model import LinearRegression

In [173]:
df = pd.read_csv('50_Startups.csv')

In [174]:
df.head()

   R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [175]:
df = np.round(pd.read_csv('50_Startups.csv')[['R&D Spend','Administration','Marketing Spend','Profit']]/10000)
np.random.seed(9)
df = df.sample(5)
df

    R&D Spend  Administration  Marketing Spend  Profit
21        8.0            15.0             30.0    11.0
37        4.0             5.0             20.0     9.0
2        15.0            10.0             41.0    19.0
14       12.0            16.0             26.0    13.0
44        2.0            15.0              3.0     7.0

In [176]:
df = df.iloc[:,0:-1]
df

    R&D Spend  Administration  Marketing Spend
21        8.0            15.0             30.0
37        4.0             5.0             20.0
2        15.0            10.0             41.0
14       12.0            16.0             26.0
44        2.0            15.0              3.0

In [177]:
df_orig = df.copy()

In [178]:
df.iloc[1,0] = np.nan
df.iloc[3,1] = np.nan
df.iloc[-1,-1] = np.nan

In [179]:
df.head()

    R&D Spend  Administration  Marketing Spend
21        8.0            15.0             30.0
37        NaN             5.0             20.0
2        15.0            10.0             41.0
14       12.0             NaN             26.0
44        2.0            15.0              NaN

# Step 1 - Impute all missing values with mean of respective col

In [117]:
df0 = pd.DataFrame()

df0['R&D Spend'] = df['R&D Spend'].fillna(df['R&D Spend'].mean())
df0['Administration'] = df['Administration'].fillna(df['Administration'].mean())
df0['Marketing Spend'] = df['Marketing Spend'].fillna(df['Marketing Spend'].mean())

In [118]:
df0.head()

    R&D Spend  Administration  Marketing Spend
21       8.00           15.00            30.00
37       9.25            5.00            20.00
2       15.00           10.00            41.00
14      12.00           11.25            26.00
44       2.00           15.00            29.25

# 0th Iteration

In [119]:

df0

    R&D Spend  Administration  Marketing Spend
21       8.00           15.00            30.00
37       9.25            5.00            20.00
2       15.00           10.00            41.00
14      12.00           11.25            26.00
44       2.00           15.00            29.25

In [120]:
# Remove the col1 imputed value
df1 = df0.copy()

df1.iloc[1,0] = np.nan

df1

    R&D Spend  Administration  Marketing Spend
21        8.0           15.00            30.00
37        NaN            5.00            20.00
2        15.0           10.00            41.00
14       12.0           11.25            26.00
44        2.0           15.00            29.25

In [121]:
# Use all rows except 1 for traning and 2nd , 3rd column only

X = df1.iloc[[0,2,3,4],1:3]
X

    Administration  Marketing Spend
21           15.00            30.00
2            10.00            41.00
14           11.25            26.00
44           15.00            29.25

In [122]:

y = df1.iloc[[0,2,3,4],0]
y

21     8.0
2     15.0
14    12.0
44     2.0
Name: R&D Spend, dtype: float64

In [123]:
lr = LinearRegression()
lr.fit(X,y)
lr.predict(df1.iloc[1,1:].values.reshape(1,2))

D:\personal\coharts\100 days of ml\.venv\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([23.14158651])

In [124]:

df1.iloc[1,0] = 23.14

In [125]:
df1

    R&D Spend  Administration  Marketing Spend
21       8.00           15.00            30.00
37      23.14            5.00            20.00
2       15.00           10.00            41.00
14      12.00           11.25            26.00
44       2.00           15.00            29.25

In [126]:
# Remove the col2 imputed value
df1.iloc[3,1] = np.nan

df1

    R&D Spend  Administration  Marketing Spend
21       8.00            15.0            30.00
37      23.14             5.0            20.00
2       15.00            10.0            41.00
14      12.00             NaN            26.00
44       2.00            15.0            29.25

In [127]:
# Use last 3 rows to build a model and use the first for prediction
X = df1.iloc[[0,1,2,4],[0,2]]
X

    R&D Spend  Marketing Spend
21       8.00            30.00
37      23.14            20.00
2       15.00            41.00
44       2.00            29.25

In [128]:
y = df1.iloc[[0,1,2,4],1]
y

21    15.0
37     5.0
2     10.0
44    15.0
Name: Administration, dtype: float64

In [129]:

lr = LinearRegression()
lr.fit(X,y)
lr.predict(df1.iloc[3,[0,2]].values.reshape(1,2))

D:\personal\coharts\100 days of ml\.venv\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([11.06331285])

In [130]:
df1.iloc[3,1] = 11.06

In [131]:
df1

    R&D Spend  Administration  Marketing Spend
21       8.00           15.00            30.00
37      23.14            5.00            20.00
2       15.00           10.00            41.00
14      12.00           11.06            26.00
44       2.00           15.00            29.25

In [132]:
# Remove the col3 imputed value
df1.iloc[4,-1] = np.nan

df1

    R&D Spend  Administration  Marketing Spend
21       8.00           15.00             30.0
37      23.14            5.00             20.0
2       15.00           10.00             41.0
14      12.00           11.06             26.0
44       2.00           15.00              NaN

In [133]:

# Use last 3 rows to build a model and use the first for prediction
X = df1.iloc[0:4,0:2]
X

    R&D Spend  Administration
21       8.00           15.00
37      23.14            5.00
2       15.00           10.00
14      12.00           11.06

In [134]:

y = df1.iloc[0:4,-1]
y

21    30.0
37    20.0
2     41.0
14    26.0
Name: Marketing Spend, dtype: float64

In [135]:
lr = LinearRegression()
lr.fit(X,y)
lr.predict(df1.iloc[4,0:2].values.reshape(1,2))

D:\personal\coharts\100 days of ml\.venv\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([31.56351448])

In [136]:
df1.iloc[4,-1] = 31.56

# After 1st Iteration

In [137]:

df1

    R&D Spend  Administration  Marketing Spend
21       8.00           15.00            30.00
37      23.14            5.00            20.00
2       15.00           10.00            41.00
14      12.00           11.06            26.00
44       2.00           15.00            31.56

# Subtract 0th iteration from 1st iteration

In [138]:


df1 - df0

    R&D Spend  Administration  Marketing Spend
21       0.00            0.00             0.00
37      13.89            0.00             0.00
2        0.00            0.00             0.00
14       0.00           -0.19             0.00
44       0.00            0.00             2.31

# 2nd iteration

In [139]:
df2 = df1.copy()

df2.iloc[1,0] = np.nan

df2

    R&D Spend  Administration  Marketing Spend
21        8.0           15.00            30.00
37        NaN            5.00            20.00
2        15.0           10.00            41.00
14       12.0           11.06            26.00
44        2.0           15.00            31.56

In [140]:
X = df2.iloc[[0,2,3,4],1:3]
y = df2.iloc[[0,2,3,4],0]

lr = LinearRegression()
lr.fit(X,y)
lr.predict(df2.iloc[1,1:].values.reshape(1,2))

D:\personal\coharts\100 days of ml\.venv\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([23.78627207])

In [141]:

df2.iloc[1,0] = 23.78

In [142]:

df2.iloc[3,1] = np.nan
X = df2.iloc[[0,1,2,4],[0,2]]
y = df2.iloc[[0,1,2,4],1]

lr = LinearRegression()
lr.fit(X,y)
lr.predict(df2.iloc[3,[0,2]].values.reshape(1,2))

D:\personal\coharts\100 days of ml\.venv\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([11.22020174])

In [143]:
df2.iloc[3,1] = 11.22

In [144]:
df2.iloc[4,-1] = np.nan

X = df2.iloc[0:4,0:2]
y = df2.iloc[0:4,-1]

lr = LinearRegression()
lr.fit(X,y)
lr.predict(df2.iloc[4,0:2].values.reshape(1,2))

D:\personal\coharts\100 days of ml\.venv\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([38.87979054])

In [145]:

df2.iloc[4,-1] = 38.87

In [146]:
df2

    R&D Spend  Administration  Marketing Spend
21       8.00           15.00            30.00
37      23.78            5.00            20.00
2       15.00           10.00            41.00
14      12.00           11.22            26.00
44       2.00           15.00            38.87

In [147]:
df2 - df1

    R&D Spend  Administration  Marketing Spend
21       0.00            0.00             0.00
37       0.64            0.00             0.00
2        0.00            0.00             0.00
14       0.00            0.16             0.00
44       0.00            0.00             7.31

# Using Iterative Imputer Scikit-Learn class

In [168]:
from sklearn.impute import IterativeImputer
from sklearn.linear_model import LinearRegression

In [169]:
# -----------------------------
# Step 2: Create IterativeImputer
# -----------------------------

imputer = IterativeImputer(
    estimator=LinearRegression(),
    max_iter=10,
    random_state=42,
    initial_strategy="mean",
    imputation_order="ascending",
    verbose=3     # Shows what happens internally
)

In [180]:
df_new = df.copy()

In [181]:
df_new

    R&D Spend  Administration  Marketing Spend
21        8.0            15.0             30.0
37        NaN             5.0             20.0
2        15.0            10.0             41.0
14       12.0             NaN             26.0
44        2.0            15.0              NaN

In [182]:
# -----------------------------
# Step 3: Fit + Transform
# -----------------------------

imputed_array = imputer.fit_transform(df_new)

[IterativeImputer] Completing matrix with shape (5, 3)
[IterativeImputer] Ending imputation round 1/10, elapsed time 0.00
[IterativeImputer] Change: 13.89158650678614, scaled tolerance: 0.041
[IterativeImputer] Ending imputation round 2/10, elapsed time 0.01
[IterativeImputer] Change: 7.788589474908925, scaled tolerance: 0.041
[IterativeImputer] Ending imputation round 3/10, elapsed time 0.01
[IterativeImputer] Change: 23.948920418409088, scaled tolerance: 0.041
[IterativeImputer] Ending imputation round 4/10, elapsed time 0.01
[IterativeImputer] Change: 7.612848445224898, scaled tolerance: 0.041
[IterativeImputer] Ending imputation round 5/10, elapsed time 0.01
[IterativeImputer] Change: 0.27235443705799867, scaled tolerance: 0.041
[IterativeImputer] Ending imputation round 6/10, elapsed time 0.01
[IterativeImputer] Change: 0.012786770349435983, scaled tolerance: 0.041
[IterativeImputer] Early stopping criterion reached.

In [183]:
imputed_array

array([[ 8.        , 15.        , 30.        ],
       [26.7182251 ,  5.        , 20.        ],
       [15.        , 10.        , 41.        ],
       [12.        , 13.02245793, 26.        ],
       [ 2.        , 15.        , 70.6926375 ]])

In [184]:
# Convert back to DataFrame
imputed_df = pd.DataFrame(
    imputed_array,
    columns=df.columns,
    index=df.index
)

In [185]:
print("\nImputed Data")
print(imputed_df)

Imputed Data
    R&D Spend  Administration  Marketing Spend
21   8.000000       15.000000        30.000000
37  26.718225        5.000000        20.000000
2   15.000000       10.000000        41.000000
14  12.000000       13.022458        26.000000
44   2.000000       15.000000        70.692637

In [186]:
df_new

    R&D Spend  Administration  Marketing Spend
21        8.0            15.0             30.0
37        NaN             5.0             20.0
2        15.0            10.0             41.0
14       12.0             NaN             26.0
44        2.0            15.0              NaN

In [187]:
df_orig

    R&D Spend  Administration  Marketing Spend
21        8.0            15.0             30.0
37        4.0             5.0             20.0
2        15.0            10.0             41.0
14       12.0            16.0             26.0
44        2.0            15.0              3.0

In [103]:
# -----------------------------
# Step 4: Inspect learned models
# -----------------------------

In [104]:
print("\nSequence of fitted estimators:\n")

for i, triplet in enumerate(imputer.imputation_sequence_):
    print(f"Step {i+1}:")
    print(triplet)
    print()

Sequence of fitted estimators:

Step 1:
_ImputerTriplet(feat_idx=np.int64(0), neighbor_feat_idx=array([1, 2]), estimator=BayesianRidge())

Step 2:
_ImputerTriplet(feat_idx=np.int64(1), neighbor_feat_idx=array([0, 2]), estimator=BayesianRidge())

Step 3:
_ImputerTriplet(feat_idx=np.int64(2), neighbor_feat_idx=array([0, 1]), estimator=BayesianRidge())

Step 4:
_ImputerTriplet(feat_idx=np.int64(0), neighbor_feat_idx=array([1, 2]), estimator=BayesianRidge())

Step 5:
_ImputerTriplet(feat_idx=np.int64(1), neighbor_feat_idx=array([0, 2]), estimator=BayesianRidge())

Step 6:
_ImputerTriplet(feat_idx=np.int64(2), neighbor_feat_idx=array([0, 1]), estimator=BayesianRidge())

Step 7:
_ImputerTriplet(feat_idx=np.int64(0), neighbor_feat_idx=array([1, 2]), estimator=BayesianRidge())

Step 8:
_ImputerTriplet(feat_idx=np.int64(1), neighbor_feat_idx=array([0, 2]), estimator=BayesianRidge())

Step 9:
_ImputerTriplet(feat_idx=np.int64(2), neighbor_feat_idx=array([0, 1]), estimator=BayesianRidge())

Step 10:
_ImputerTriplet(feat_idx=np.int64(0), neighbor_feat_idx=array([1, 2]), estimator=BayesianRidge())

Step 11:
_ImputerTriplet(feat_idx=np.int64(1), neighbor_feat_idx=array([0, 2]), estimator=BayesianRidge())

Step 12:
_ImputerTriplet(feat_idx=np.int64(2), neighbor_feat_idx=array([0, 1]), estimator=BayesianRidge())