In [28]:
import pandas as pd


from sklearn.model_selection import train_test_split,cross_val_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.compose import ColumnTransformer

In [2]:
df = pd.read_csv('train.csv', usecols=['Age','Fare','SibSp','Parch','Survived'])

In [3]:
df

     Survived   Age  SibSp  Parch     Fare
0           0  22.0      1      0   7.2500
1           1  38.0      1      0  71.2833
2           1  26.0      0      0   7.9250
3           1  35.0      1      0  53.1000
4           0  35.0      0      0   8.0500
..        ...   ...    ...    ...      ...
886         0  27.0      0      0  13.0000
887         1  19.0      0      0  30.0000
888         0   NaN      1      2  23.4500
889         1  26.0      0      0  30.0000
890         0  32.0      0      0   7.7500

[891 rows x 5 columns]

In [4]:

df.dropna(inplace=True)

In [5]:

df.head()

   Survived   Age  SibSp  Parch     Fare
0         0  22.0      1      0   7.2500
1         1  38.0      1      0  71.2833
2         1  26.0      0      0   7.9250
3         1  35.0      1      0  53.1000
4         0  35.0      0      0   8.0500

In [6]:

df['family'] = df['SibSp'] + df['Parch']

In [7]:

df.head()

   Survived   Age  SibSp  Parch     Fare  family
0         0  22.0      1      0   7.2500       1
1         1  38.0      1      0  71.2833       1
2         1  26.0      0      0   7.9250       0
3         1  35.0      1      0  53.1000       1
4         0  35.0      0      0   8.0500       0

In [8]:
df.drop(columns=['SibSp','Parch'],inplace=True)

In [9]:
df.head()

   Survived   Age     Fare  family
0         0  22.0   7.2500       1
1         1  38.0  71.2833       1
2         1  26.0   7.9250       0
3         1  35.0  53.1000       1
4         0  35.0   8.0500       0

In [10]:
X = df.drop(columns=['Survived'])
y = df['Survived']

In [12]:
y

0      0
1      1
2      1
3      1
4      0
      ..
885    0
886    0
887    1
889    1
890    0
Name: Survived, Length: 714, dtype: int64

In [15]:

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [17]:

X_train.shape

(571, 3)

In [37]:
X_train.head()

      Age     Fare  family
328  31.0  20.5250       1
73   26.0  14.4542       1
253  30.0  16.1000       1
719  33.0   7.7750       0
666  25.0  13.0000       0

In [22]:

# Without binarization

clf = DecisionTreeClassifier()

clf.fit(X_train,y_train)

y_pred = clf.predict(X_test)

accuracy_score(y_test,y_pred)

0.6223776223776224

In [24]:
import numpy as np

In [25]:

np.mean(cross_val_score(DecisionTreeClassifier(),X_train,y_train,cv=10,scoring='accuracy'))

np.float64(0.6568360556563824)

In [26]:

# Applying Binarization

from sklearn.preprocessing import Binarizer

In [29]:

trf = ColumnTransformer([
    ('bin',Binarizer(copy=False),['family'])
],remainder='passthrough')

In [30]:
X_train_trf = trf.fit_transform(X_train)
X_test_trf = trf.transform(X_test)

In [31]:
pd.DataFrame(X_train_trf,columns=['family','Age','Fare'])

     family   Age      Fare
0       1.0  31.0   20.5250
1       1.0  26.0   14.4542
2       1.0  30.0   16.1000
3       0.0  33.0    7.7750
4       0.0  25.0   13.0000
..      ...   ...       ...
566     1.0  46.0   61.1750
567     0.0  25.0   13.0000
568     0.0  41.0  134.5000
569     1.0  33.0   20.5250
570     0.0  33.0    7.8958

[571 rows x 3 columns]

In [34]:
X_train_trf

array([[  1.    ,  31.    ,  20.525 ],
       [  1.    ,  26.    ,  14.4542],
       [  1.    ,  30.    ,  16.1   ],
       ...,
       [  0.    ,  41.    , 134.5   ],
       [  1.    ,  33.    ,  20.525 ],
       [  0.    ,  33.    ,   7.8958]], shape=(571, 3))

In [35]:

clf = DecisionTreeClassifier()
clf.fit(X_train_trf,y_train)
y_pred2 = clf.predict(X_test_trf)

accuracy_score(y_test,y_pred2)

0.5944055944055944

In [36]:
np.mean(cross_val_score(DecisionTreeClassifier(),X_train_trf,y_train,cv=10,scoring='accuracy'))

np.float64(0.6375680580762251)