In [1]:
import pandas as pd
import numpy as np

In [2]:
date = pd.read_csv('orders.csv')
time = pd.read_csv('messages.csv')

In [3]:
time.info()
date.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   str
 1   msg     1000 non-null   str
dtypes: str(2)
memory usage: 15.8 KB
<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   str
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: int64(3), str(1)
memory usage: 31.4 KB

## 1. Working with Dates

In [4]:
date

           date  product_id  city_id  orders
0    2019-12-10        5628       25       3
1    2018-08-15        3646       14     157
2    2018-10-23        1859       25       1
3    2019-08-17        7292       25       1
4    2019-01-06        4344       25       3
..          ...         ...      ...     ...
995  2018-10-08         255       13       1
996  2018-12-06        5521        7       1
997  2019-05-07         487       26      14
998  2019-03-03        1503       21       2
999  2019-10-15        6371        7      22

[1000 rows x 4 columns]

In [5]:
date['date'] = pd.to_datetime(date['date'], 
                              format = '%Y-%m-%d', errors='coerce')

## a. Extract Year

In [6]:
date['date_year'] = date['date'].dt.year

In [7]:
date.sample(5)

          date  product_id  city_id  orders  date_year
494 2019-03-05        4733       12       2       2019
195 2019-05-01        5470       16      23       2019
295 2018-10-29        3012       18       3       2018
929 2019-12-07        6801        3       7       2019
70  2019-10-29        6443       16       1       2019

## b. Extract Month

In [8]:
date['date_month'] = date['date'].dt.month

In [9]:
date

          date  product_id  city_id  orders  date_year  date_month
0   2019-12-10        5628       25       3       2019          12
1   2018-08-15        3646       14     157       2018           8
2   2018-10-23        1859       25       1       2018          10
3   2019-08-17        7292       25       1       2019           8
4   2019-01-06        4344       25       3       2019           1
..         ...         ...      ...     ...        ...         ...
995 2018-10-08         255       13       1       2018          10
996 2018-12-06        5521        7       1       2018          12
997 2019-05-07         487       26      14       2019           5
998 2019-03-03        1503       21       2       2019           3
999 2019-10-15        6371        7      22       2019          10

[1000 rows x 6 columns]

In [10]:
date['date_month_name'] = date['date'].dt.month_name()

In [11]:
date

,date,product_id,city_id,orders,date_year,date_month,date_month_name
0,2019-12-10,5628,25,3,2019,12,December
1,2018-08-15,3646,14,157,2018,8,August
2,2018-10-23,1859,25,1,2018,10,October
3,2019-08-17,7292,25,1,2019,8,August
4,2019-01-06,4344,25,3,2019,1,January
...,...,...,...,...,...,...,...
995,2018-10-08,255,13,1,2018,10,October
996,2018-12-06,5521,7,1,2018,12,December
997,2019-05-07,487,26,14,2019,5,May
998,2019-03-03,1503,21,2,2019,3,March
999,2019-10-15,6371,7,22,2019,10,October

## c. Extract Day

In [12]:
date['date_day'] = date['date'].dt.day
date.head()

,date,product_id,city_id,orders,date_year,date_month,date_month_name,date_day
0,2019-12-10,5628,25,3,2019,12,December,10
1,2018-08-15,3646,14,157,2018,8,August,15
2,2018-10-23,1859,25,1,2018,10,October,23
3,2019-08-17,7292,25,1,2019,8,August,17
4,2019-01-06,4344,25,3,2019,1,January,6

In [13]:
date['date_dow'] = date['date'].dt.day_of_week
date.head()

,date,product_id,city_id,orders,date_year,date_month,date_month_name,date_day,date_dow
0,2019-12-10,5628,25,3,2019,12,December,10,1
1,2018-08-15,3646,14,157,2018,8,August,15,2
2,2018-10-23,1859,25,1,2018,10,October,23,1
3,2019-08-17,7292,25,1,2019,8,August,17,5
4,2019-01-06,4344,25,3,2019,1,January,6,6

In [14]:
date['date_dow_name'] = date['date'].dt.day_name()
date.head()

,date,product_id,city_id,orders,date_year,date_month,date_month_name,date_day,date_dow,date_dow_name
0,2019-12-10,5628,25,3,2019,12,December,10,1,Tuesday
1,2018-08-15,3646,14,157,2018,8,August,15,2,Wednesday
2,2018-10-23,1859,25,1,2018,10,October,23,1,Tuesday
3,2019-08-17,7292,25,1,2019,8,August,17,5,Saturday
4,2019-01-06,4344,25,3,2019,1,January,6,6,Sunday

In [15]:
date['date_is_weekend'] = np.where(date['date_dow_name'].isin(['Sunday', 'Saturday']), 1,0)

In [16]:
date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month,date_month_name,date_day,date_dow,date_dow_name,date_is_weekend
0,2019-12-10,2019,12,December,10,1,Tuesday,0
1,2018-08-15,2018,8,August,15,2,Wednesday,0
2,2018-10-23,2018,10,October,23,1,Tuesday,0
3,2019-08-17,2019,8,August,17,5,Saturday,1
4,2019-01-06,2019,1,January,6,6,Sunday,1

## d. Extract Week of the Year

In [17]:
date['date_week'] = date['date'].dt.day_of_week
date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month,date_month_name,date_day,date_dow,date_dow_name,date_is_weekend,date_week
0,2019-12-10,2019,12,December,10,1,Tuesday,0,1
1,2018-08-15,2018,8,August,15,2,Wednesday,0,2
2,2018-10-23,2018,10,October,23,1,Tuesday,0,1
3,2019-08-17,2019,8,August,17,5,Saturday,1,5
4,2019-01-06,2019,1,January,6,6,Sunday,1,6

## e. Extract Quarter

In [18]:
date['quarter'] = date['date'].dt.quarter
date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month,date_month_name,date_day,date_dow,date_dow_name,date_is_weekend,date_week,quarter
0,2019-12-10,2019,12,December,10,1,Tuesday,0,1,4
1,2018-08-15,2018,8,August,15,2,Wednesday,0,2,3
2,2018-10-23,2018,10,October,23,1,Tuesday,0,1,4
3,2019-08-17,2019,8,August,17,5,Saturday,1,5,3
4,2019-01-06,2019,1,January,6,6,Sunday,1,6,1

## f. Extract Semeaster

In [19]:
date['semester'] = np.where(date['quarter'].isin([1,2]), 1, 2)
date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month,date_month_name,date_day,date_dow,date_dow_name,date_is_weekend,date_week,quarter,semester
0,2019-12-10,2019,12,December,10,1,Tuesday,0,1,4,2
1,2018-08-15,2018,8,August,15,2,Wednesday,0,2,3,2
2,2018-10-23,2018,10,October,23,1,Tuesday,0,1,4,2
3,2019-08-17,2019,8,August,17,5,Saturday,1,5,3,2
4,2019-01-06,2019,1,January,6,6,Sunday,1,6,1,1

## G. Extract Time Elasped b/w two dates

In [20]:
import datetime
today = datetime.datetime.today()

In [21]:
today

datetime.datetime(2026, 7, 25, 16, 59, 6, 104833)

In [22]:

today - date['date']

0     2419 days 16:59:06.104833
1     2901 days 16:59:06.104833
2     2832 days 16:59:06.104833
3     2534 days 16:59:06.104833
4     2757 days 16:59:06.104833
                 ...
995   2847 days 16:59:06.104833
996   2788 days 16:59:06.104833
997   2636 days 16:59:06.104833
998   2701 days 16:59:06.104833
999   2475 days 16:59:06.104833
Name: date, Length: 1000, dtype: timedelta64[us]

In [23]:

(today - date['date']).dt.days

0      2419
1      2901
2      2832
3      2534
4      2757
       ...
995    2847
996    2788
997    2636
998    2701
999    2475
Name: date, Length: 1000, dtype: int64

In [24]:
# Calculate exact difference in calendar months
date['months_passed'] = (today.year - date['date'].dt.year) * 12 + (today.month - date['date'].dt.month)

In [25]:
date

,date,product_id,city_id,orders,date_year,date_month,date_month_name,date_day,date_dow,date_dow_name,date_is_weekend,date_week,quarter,semester,months_passed
0,2019-12-10,5628,25,3,2019,12,December,10,1,Tuesday,0,1,4,2,79
1,2018-08-15,3646,14,157,2018,8,August,15,2,Wednesday,0,2,3,2,95
2,2018-10-23,1859,25,1,2018,10,October,23,1,Tuesday,0,1,4,2,93
3,2019-08-17,7292,25,1,2019,8,August,17,5,Saturday,1,5,3,2,83
4,2019-01-06,4344,25,3,2019,1,January,6,6,Sunday,1,6,1,1,90
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,2018-10-08,255,13,1,2018,10,October,8,0,Monday,0,0,4,2,93
996,2018-12-06,5521,7,1,2018,12,December,6,3,Thursday,0,3,4,2,91
997,2019-05-07,487,26,14,2019,5,May,7,1,Tuesday,0,1,2,1,86
998,2019-03-03,1503,21,2,2019,3,March,3,6,Sunday,1,6,1,1,88
999,2019-10-15,6371,7,22,2019,10,October,15,1,Tuesday,0,1,4,2,81

In [26]:
time.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   str
 1   msg     1000 non-null   str
dtypes: str(2)
memory usage: 15.8 KB

In [27]:
time.sample(5)

                    date                                                msg
44   2016-07-01 23:42:00  Есть толковый парень? желательно без пошлостей...
419  2013-10-15 01:26:00  Пообщаюсь с приятной ДЕВУШКОЙ Мне 30 Макс Днеп...
603  2016-02-27 01:24:00  МОЛОДОЙ ПАРЕНЬ ПОЗНАКОМИТСЯ С ГОРЯЧЕЙ ДЕВУШКОЙ...
476  2015-08-12 00:34:00  приглашаю дев сем пару прогулятся по набережно...
696  2016-09-23 00:23:00                              для\tОльги 0684607724

In [28]:

# Converting to datetime datatype
time['date'] = pd.to_datetime(time['date'])

In [29]:

time.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   datetime64[us]
 1   msg     1000 non-null   str
dtypes: datetime64[us](1), str(1)
memory usage: 15.8 KB

time

## H. Extract time part from cell contain date and timestamp both

In [30]:
time['time'] = time['date'].dt.time

time.head()

,date,msg,time
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,00:50:00
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23:40:00
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,00:21:00
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,00:31:00
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23:11:00

## I. Time difference

In [31]:
today - time['date']

0     4605 days 16:09:06.104833
1     4469 days 17:19:06.104833
2     4955 days 16:38:06.104833
3     4257 days 16:28:06.104833
4     4654 days 17:48:06.104833
                 ...
995   5244 days 16:09:06.104833
996   4565 days 17:45:06.104833
997   5030 days 17:22:06.104833
998   5146 days 17:25:06.104833
999   4418 days 17:34:06.104833
Name: date, Length: 1000, dtype: timedelta64[us]

In [32]:

# in seconds

(today - time['date'])/np.timedelta64(1,'s')

0      3.979301e+08
1      3.861839e+08
2      4.281719e+08
3      3.678641e+08
4      4.021697e+08
           ...
995    4.531397e+08
996    3.944799e+08
997    4.346545e+08
998    4.446771e+08
999    3.817784e+08
Name: date, Length: 1000, dtype: float64

In [33]:

# in minutes

(today - time['date'])/np.timedelta64(1,'m')

0      6.632169e+06
1      6.436399e+06
2      7.136198e+06
3      6.131068e+06
4      6.702828e+06
           ...
995    7.552329e+06
996    6.574665e+06
997    7.244242e+06
998    7.411285e+06
999    6.362974e+06
Name: date, Length: 1000, dtype: float64

In [34]:

# in hours

(today - time['date'])/np.timedelta64(1,'h')

0      110536.151696
1      107273.318362
2      118936.635029
3      102184.468362
4      111713.801696
           ...
995    125872.151696
996    109577.751696
997    120737.368362
998    123521.418362
999    106049.568362
Name: date, Length: 1000, dtype: float64